version: 2

builds:
  - binary: service-generator
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: service-generator
    homepage: https://github.com/oneaccord-llc/service-generator
    commit_author:
      name: ONEaccord
